### ISSUE TITLE
PLIP installation problem

### ISSUE THREAD

**Issue by frchalaoux** [ssalentin/plip#1]
I’m trying to install PLIP on my Linux machine and got an error during setting.
Pymol 1.8.0.2 from Schrodinger is installed on this linux machine but I don’t understand the error (see below).

Does it need a pymol python module, where should be this module ?

Cheers, FR.

ERROR:
=======
Processing dependencies for plip==1.2.0
Searching for pymol
Reading https://pypi.python.org/simple/pymol/
No local packages or download links found for pymol
error: Could not find suitable distribution for Requirement.parse('pymol')

**Comment by ssalentin** [comment]
I removed the pymol dependency in the latest commit d683a34d44a5d5ff299b0f47472a54cc949ebbac . Also updated the on PyPi -> [PLIP v1.2.2a](https://pypi.python.org/pypi/plip/1.2.2a). The dependency was a remainder from an internal test system. PyMOL and the corresponding Python bindings need to be installed independently.
