### ISSUE TITLE
Is 1.3.5 ready for python 3?

### ISSUE THREAD

**Issue by o7o** [ssalentin/plip#11]
If it's right, what version of python 3, the 1.3.5 ready? Is 3.5, 3.6, or 3.7 version?

Thanks

BS

note: I tried this version (1.3.5) using python 2.7.13, pymol 1.7.6 for windows and got error result for 1bju.pdb

**Comment by ssalentin** [comment]
Full support for Python 3 will be available in the next version PLIP 1.4 . Until now, some things have been prepared. 

Is the problem with 1bju related to issue #5 ?

**Comment by o7o** [comment]
Thanks for your info, but this error, I think, did not related to maxthreads' problem but it can be cause the same problem with #9

**Comment by ssalentin** [comment]
Full compatibility for Python 3 was added in commit 0a4a51ae4bc645a02311dddddeacf385aa7acba5 of the development branch. Is still backwards-compatible to Python 2.7. Feedback greatly appreciated. Version was tested on Python 3.5.
