### ISSUE TITLE
XMLParser: MetalComplex'es have no ligcoo and protcoo

### ISSUE THREAD

**Issue by xrobin** [ssalentin/plip#17]
In the XML parser, when I have a metal complex (say `complex = pm.bsites['CU:_:2'].metal_complexes[0]`) and I get the `ligcoo` or `protcoo` attributes, I get an empty list `[]` instead of a coordinates tuple.

This makes sense when I look at the XML itself: there is indeed no ligcoo/protcoo but instead `metalcoo` and `targetcoo`.

At this point I'm not sure if it's an issue with documentation (which has: "All | ligcoo" and "All | protcoo") or the XML writer in plipcmd. What is the reason to use different XML elements for metal complexes?

**Comment by ssalentin** [comment]
The documentation was incomplete and has been updated.
While the clear separation into "ligand" and "protein" coordinates is fine for all other interaction types, it doesn't work with metal coordination. Here, a metal atoom is coordinated by groups which can be either found in an adjacent ligand or the protein binding site. This is why I chose `metalcoo` and `targetcoo` as names
