### ISSUE TITLE
Can't process large structures with more than 99999 atoms

### ISSUE THREAD

**Issue by xrobin** [ssalentin/plip#19]
An example is [4V9O](http://www.rcsb.org/structure/4V9O):

    $ plipcmd -i 4V9O
    Error:  No file in PDB format available from wwPDB for the given PDB ID.

I currently have the structure stored in an "invalid" PDB format where atoms > 99999 are replaced by *****, but PLIP can't read the file:
```
/scicore/home/schwede/zohixe92/SMNG/stage/bin/sm run-plip -f /scicore/home/schwede/zohixe92/SMTL_ribosome/entries/4v/9o/biounit.1.pdb -o /scicore/home/schwede/zohixe92/SMTL_ribosome/entries/4v/9o --name plip_report.1 -x
Traceback (most recent call last):
  File "/opt/pliptool/plip/plipcmd", line 291, in <module>
    main(expanded_path, arguments.pdbid)  # Start main script
  File "/opt/pliptool/plip/plipcmd", line 152, in main
    process_pdb(inputstruct, config.OUTPATH, as_string=read_from_stdin, outputprefix=outputprefix)
  File "/opt/pliptool/plip/plipcmd", line 57, in process_pdb
    mol.load_pdb(pdbfile, as_string=as_string)
  File "/opt/pliptool/plip/modules/preparation.py", line 1286, in load_pdb
    pdbparser = PDBParser(pdbpath, as_string=as_string)  # Parse PDB file to find errors and get additonal data
  File "/opt/pliptool/plip/modules/preparation.py", line 28, in __init__
    self.proteinmap, self.modres, self.covalent, self.altconformations, self.corrected_pdb = self.parse_pdb()
  File "/opt/pliptool/plip/modules/preparation.py", line 61, in parse_pdb
    corrected_line, newnum = self.fix_pdbline(line, lastnum)
  File "/opt/pliptool/plip/modules/preparation.py", line 128, in fix_pdbline
    currentnum = int(pdbline[6:11])
ValueError: invalid literal for int() with base 10: '*****'
```
An alternative would be to read files in the mmCIF format, but that doesn't seem possible at the moment either.

I believe there are currently [482 structures with > 99999 atoms on PDB](http://www.rcsb.org/pdb/results/results.do?tabtoshow=Current&qrid=CE55430E&startAt=0&newsortfield=Residue%20Count%20Descending) that I'd like to analyze.

**Comment by ssalentin** [comment]
Correct, PLIP only supports PDB files as input.
An option would be to use split PDB files, which are provided by PDB, see e.g. [here]( https://files.rcsb.org/pub/pdb/compatible/pdb_bundle/v9/4v9o/4v9o-pdb-bundle.tar.gz) for 4V9O.

**Comment by xrobin** [comment]
Browsing through the code to see how to "fix" the PDF files, I can see in supplemental.py, line 412 (readmol):

    supported_formats = ['pdb', 'mmcif']

This suggests one could read the PDBx/mmCIF files from PDB. However it isn't working and I get the following error:

```
$ wget https://files.rcsb.org/download/2UV8.cif
$ plipcmd -f 2UV8.cif -Ot --nofix --debug

**********************************************
* Protein-Ligand Interaction Profiler v1.4.0 *
**********************************************


Starting analysis of 2UV8.cif
=================================
Debug:  Detected pdb as format. Now trying to read file with OpenBabel...
Error:  No valid file format provided.
```
How difficult would it be to turn on mmcif/cif support, if possible at all?

**Comment by xrobin** [comment]
Ok, good to know!

I found a workaround in the meantime. Using [OpenStructure](https://openstructure.org/) I can select all the residues that are within 15A of any ligand atom. I can then save only those atoms in a PDB file. With 4v9o (that has hundreds of ligands) that leaves only ~ 85000 atoms, which just fit in a PDB file. It is possible that a few other structures may remain over 99999 atoms, but I haven't found an example yet.

I checked a few smaller structures manually. The only difference I could notice in the XML output seems to be the atom numbering of course, and sometimes the order in which the interactions are reported, especially metal complexes. Can I expect it to be the case for all structures, or could it make some more major changes in the bond detection?

**Comment by ssalentin** [comment]
Good to hear you found a solution for these cases.
The interaction data itself should be not changed as long as the binding site selection is large enough (15A should should be more than sufficient).
We already did similar preparation of structures for some large ribosome complexes and it worked fine. However, we never systematically tested it.
If you find any serious inconsistencies, let me know and I can have a look how to adress that.
