### ISSUE TITLE
Example of python library

### ISSUE THREAD

**Issue by anasves** [ssalentin/plip#20]
This piece of code was not working for me (in 2. Run PLIP - as a python library):

print [pistack.resnr for pistack in s.pistacking] # NameError: name 's' is not defined

I am not sure whether that is how it was supposed to be but with: 
           print [pistack.resnr for pistack in my_interactions.pistacking] 
actually prints [84, 129]

**Comment by ssalentin** [comment]
This was an error in the documentation.
It is fixed now in `stable` . The correct code is as follows:

```python
from plip.modules.preparation import PDBComplex

my_mol = PDBComplex()
my_mol.load_pdb('/tmp/1EVE.pdb') # Load the PDB file into PLIP class
print my_mol # Shows name of structure and ligand binding sites
my_bsid = 'E20:A:2001' # Unique binding site identifier (HetID:Chain:Position)
my_mol.analyze()
my_interactions = my_mol.interaction_sets[my_bsid] # Contains all interaction data

# Now print numbers of all residues taking part in pi-stacking
print [pistack.resnr for pistack in my_interactions.pistacking] # Prints [84, 129]
```

The output is correct, as it lists the residue numbers of all residues participating in pi-stacking. If you want other data, have a look at the other class properties.
