### ISSUE TITLE
--name OUTPUTFILENAME not available in 1.4.1

### ISSUE THREAD

**Issue by xrobin** [ssalentin/plip#22]
I'm sorry I'm realizing this only now, as I'm rebuilding our singularity container to get it into an lmod module. It appears that the `--name` option didn't make it to v1.4.1 but is only available in the `master` branch which wasn't merged before the release.

Is it possible to have a new release with the `--name` option available?

**Comment by ssalentin** [comment]
The option `--name` and the fixes from issues #21 and #23 are now available in PLIP 1.4.2 .
New version also available on [PyPi](https://pypi.org/project/plip/)
