### ISSUE TITLE
restype_lig and other text fields converted to float

### ISSUE THREAD

**Issue by xrobin** [ssalentin/plip#23]
I just ran into an issue with [1HDQ](http://www.rcsb.org/structure/1HDQ), where the ligand, [INF](https://www3.rcsb.org/ligand/INF), is wrongly converted to a floating point number representation of positive infinity, which causes issues downstream.

```
plipcmd -i 1hdq -x
```
And then:
```
>>> import plip.modules.plipxml as plip
>>> report = plip.PLIPXML("report.xml")
>>> print(report.bsites['INF:A:1308'].hydrophobics[0].restype_lig)
inf
>>> print(type(report.bsites['INF:A:1308'].hydrophobics[0].restype_lig))
<type 'float'>
```
When dumped into json the ligand name becomes `Infinity` (without quotes) instead of `'INF'` (with quotes) so I cannot get the ligand back. When dumped with `ujson` an `OverflowError` is raised.

There are other ligand names which can be interpreted as numbers, for instance [1ONY](http://www.rcsb.org/structure/1ONY) has a ligand named [588](https://www3.rcsb.org/ligand/588), and a ligand named [NAN](https://www3.rcsb.org/ligand/NAN) exists, although it isn't used in any PDB entry so far.

**Comment by ssalentin** [comment]
Merged pull request.
