### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by PhilippMatthes** [ssalentin/plip#26]
Because this project is already on GitHub, it would be a great thing in my opinion to set up continuous integration for this repository to improve code quality and cross-check pull requests. A good example for continuous integration can be found on our TU Dresden INLOOP-Project at [https://github.com/st-tu-dresden/inloop](https://github.com/st-tu-dresden/inloop). We use Travis and Codacy to review our code before merging it in master and deploying it on our servers. As in Pull Request [https://github.com/st-tu-dresden/inloop/pull/217](https://github.com/st-tu-dresden/inloop/pull/217) in our INLOOP Repository, one can see how the commited code is only passed-through after the code checks are positive. Setting up continuous integration (CI) is also very simple and can be done right away. Therefore I would propose CI for this repository. What do you think about it @ssalentin?

**Comment by ssalentin** [comment]
Hi Philipp, 

we have CI in place on our local GitLab instance, where PLIP releases are tested beforehand.
We might consider adding it here, too.
For now, I will close the issue.
