### ISSUE TITLE
plipcmd not in the good directory

### ISSUE THREAD

**Issue by PhilippeNoel1** [ssalentin/plip#28]
Hi,

While I cloned the repo, the first time I tried to launch plip, I got the following error : 
```Traceback` (most recent call last):  
  File "plipcmd", line 12, in <module>  
    from plip.modules.preparation import *  
ModuleNotFoundError: No module named 'plip'```

It seem the plipcmd should be in the upper directory. Or the import should be modules.preparation and not pip.odeules.preparation.

**Comment by ssalentin** [comment]
We changed that with the pull request d4b48d3 .
I added a fallback now for imports, it will try to import with the `plip.` prefix first, otherwise it will try without the prefix. Added in commit  a7d3e31 in `stable`
