### ISSUE TITLE
plipcmd returns IndexError with PDBID 3q45

### ISSUE THREAD

**Issue by flobosg** [ssalentin/plip#3]
Hi, 

`plipcmd` raises an IndexError when PDB ID [3q45](http://www.rcsb.org/pdb/explore.do?structureId=3q45) is used as an input. Apparently it has to do with the metal complex detection step. Here is the sample output:

    $ plipcmd -v -i 3q45

    **********************************************
    * Protein-Ligand Interaction Profiler v1.3.1 *
    **********************************************

    Checking status of PDB ID 3q45 ... entry is up to date.
    Downloading file from PDB ... file downloaded as ./3q45.pdb

    Starting analysis of 3q45.pdb
    ===============================
    PDB structure successfully read.
    Analyzing 9 ligands...

    MG-DAL-VAL [SMALLMOLECULE+ION] -- MG:D:1604 + DAL:D:24...
    ----------------------------------------------------------
      Binding site atoms in vicinity (7.5 A max. dist: 216).
      Reduced number of hydrophobic contacts from 15 to 6.
      Metal ion Mg complexed with square.planar geometry (coo. number 4/ 4 observed).
      Ligand interacts with 14 binding site residue(s) in chain(s) D.
      Complex uses 3 salt bridge(s), 5 hydrogen bond(s).

    MG-DAL-VAL [SMALLMOLECULE+ION] -- MG:E:1605 + DAL:E:24...
    ----------------------------------------------------------
      Binding site atoms in vicinity (7.5 A max. dist: 214).
      Reduced number of hydrophobic contacts from 14 to 8.
      Metal ion Mg complexed with square.planar geometry (coo. number 4/ 4 observed).
      Ligand interacts with 17 binding site residue(s) in chain(s) E.
      Complex uses 3 salt bridge(s), 6 hydrogen bond(s).

    MG-DAL-VAL [SMALLMOLECULE+ION] -- MG:H:1608 + DAL:H:24...
    ----------------------------------------------------------
      Binding site atoms in vicinity (7.5 A max. dist: 219).
      Reduced number of hydrophobic contacts from 15 to 8.
      Metal ion Mg complexed with trigonal.pyramidal geometry (coo. number 3/ 6 observed).
      Ligand interacts with 17 binding site residue(s) in chain(s) H.
      Complex uses 3 salt bridge(s), 7 hydrogen bond(s).

    MG-DAL-VAL [SMALLMOLECULE+ION] -- MG:I:1609 + DAL:I:24...
    ----------------------------------------------------------
      Binding site atoms in vicinity (7.5 A max. dist: 217).
      Reduced number of hydrophobic contacts from 19 to 10.
      Metal ion Mg complexed with square.planar geometry (coo. number 4/ 6 observed).
      Ligand interacts with 17 binding site residue(s) in chain(s) I.
      Complex uses 3 salt bridge(s), 5 hydrogen bond(s).

    MG-DAL-VAL [SMALLMOLECULE+ION] -- MG:B:1602 + DAL:B:24...
    ----------------------------------------------------------
      Binding site atoms in vicinity (7.5 A max. dist: 213).
      Reduced number of hydrophobic contacts from 15 to 8.
    Traceback (most recent call last):
      File "/.../plip/plipcmd", line 321, in <module>
        main(expanded_path, arguments.pdbid)  # Start main script
      File "/.../plip/plipcmd", line 224, in main
        process_pdb(pdbpath, config.OUTPATH)
      File "/.../plip/plipcmd", line 80, in process_pdb
        mol.characterize_complex(ligand)
      File "/.../plip/modules/preparation.py", line 1281, in characterize_complex
        pli_obj = PLInteraction(lig_obj, bs_obj, self)
      File "/.../plip/modules/preparation.py", line 512, in __init__
        self.bindingsite.metal_binding)
      File "/.../plip/modules/detection.py", line 365, in metal_complexation
        next_total = all_total[i + 1]
    IndexError: list index out of range

## System information

* PLIP 1.3.1
* Ubuntu 14.04.5 LTS
* Open Babel 2.3.2+dfsg-1.1
* PyMOL 1.7.0.0
* ImageMagick 6.7.7-10 2016-06-01 Q16

**Comment by ssalentin** [comment]
Thanks for the bug report. Is fixed in latest commit de73ec106170f74a86b5d10a38be901824b3bb1e and stable version 1.3.2.
