### ISSUE TITLE
request for feature: project isolated ligand or protein into pharmacophore feature space

### ISSUE THREAD

**Issue by UnixJunkie** [ssalentin/plip#39]
Hello,

Currently, PLIP does the interaction calculation only for protein-ligand complexes.

Would it be possible to detect and list possible interaction sites for a ligand or a protein only?

It is OK for one atom to be listed with several possible interactions.

Regards,
Francois.

**Comment by ssalentin** [comment]
Hi Francois,

we don't plan to integrate such a feature soon.
However, there is currently a way how to retrieve this data if you run a PLIP analysis within a Python script and then access the features in the classes `BindingSite` and `Ligand`. 
Have a look [here](https://github.com/ssalentin/plip/blob/stable/README.md) how to run a basic analysis directly from Python. Accessing the features is currently undocumented.

Best
Sebastian

**Comment by UnixJunkie** [comment]
Cool, I will play with it one day.

**Comment by UnixJunkie** [comment]
In this case, you always need a protein-ligand complex, right?
You cannot run the ph4-feature detection on an isolated ligand or protein?
