### ISSUE TITLE
Would it be possible to add a {-c|--chimera} option?

### ISSUE THREAD

**Issue by UnixJunkie** [ssalentin/plip#41]
So that users can load PLIP results into UCSF chimera?
I know about the -y|--pymol option, but I am a chimera user...
To create graphical annotations for UCSF chimera, this file format
is quite useful:
https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/bild.html
Regards,
Francois.

**Comment by UnixJunkie** [comment]
Do you have an example python session using this code?
Maybe don't close this issue.
You can leave it open and assign it to me.
I may look at implementing it when I have time.

**Comment by vjhaupt** [comment]
@UnixJunkie, if you are still planning to implement this feature, please let me know and I will reopen the issue.
