### ISSUE TITLE
Segfault with Python 3.6

### ISSUE THREAD

**Issue by PatWalters** [ssalentin/plip#42]
The example ln the README segfaults with Python 3.6

Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from plip.modules.preparation import PDBComplex

In [2]: my_mol = PDBComplex()

In [3]: my_mol.load_pdb('1EVE.pdb')

In [4]: print(my_mol)
Protein structure 1eve with ligands:
NAG:A:3002
NAG:A:3001
NAG:A:3004
NAG:A:3005
E20:A:2001

In [5]: my_bsid = 'E20:A:2001'

In [6]: my_mol.analyze()
[1]    29106 segmentation fault (core dumped)  ipython

**Comment by ssalentin** [comment]
I cannot reproduce this error. The example runs through fine on Python 3.6.6.

```python
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from plip.modules.preparation import PDBComplex                         

In [2]: my_mol = PDBComplex()                                                   

In [3]: my_mol.load_pdb('1EVE.pdb')                                             

In [4]: print(my_mol)                                                           
Protein structure 1eve with ligands:
NAG:A:3002
NAG:A:3001
NAG:A:3004
NAG:A:3005
E20:A:2001

In [5]: my_bsid = 'E20:A:2001'                                                  

In [6]: my_mol.analyze()                                                        

In [7]: my_interactions = my_mol.interaction_sets[my_bsid]                      

In [8]: print([pistack.resnr for pistack in my_interactions.pistacking])        
[84, 279]
```

I attached a file listing the packages and versions used in my Conda environment.

[req.txt](https://github.com/ssalentin/plip/files/2735659/req.txt)

**Comment by PatWalters** [comment]
Thanks!  That did the trick.  In case anyone else tries this, I also had to add the openbabel channel to conda. 
conda config --add channels openbabel

**Comment by ssalentin** [comment]
Great to hear it worked now. Thanks for the feedback.
