### ISSUE TITLE
Not supporting for multicore in Windows enviroment

### ISSUE THREAD

**Issue by o7o** [ssalentin/plip#5]
when I did not set --maxthread to 1, plip did not work well. I got loop process in something like "..multiprocessing/fork.."
Plip can work again when we set 1 core.

Would you like to add this feature in the future update.

Thanks

**Comment by ssalentin** [comment]
Could you provide me with the specific error message you get?

**Comment by o7o** [comment]
Sorry for late reply

here it is the screenshoot for error multicore (win7 64bit, python 2.7 32bit)
<pre><code>link: https://goo.gl/NZbe6Z</code></pre>
different for Ubuntu 16.04, and I am sorry, it used python 2.7 version, right as ricrogz said.
<pre><code>link: https://goo.gl/4lbmR9</code></pre>

Help me, I have tried in other Win 7 64bit system using python 2.7 64bit, but I got some error
<pre><code>link: https://goo.gl/ij9weO</code></pre>

Thank you very much

![error multicore-win764bit-py2732bit](https://cloud.githubusercontent.com/assets/4411088/21377174/8a80beae-c76e-11e6-8a3b-d9ef2113d1e3.png)
![plip-other-win7-64bit-py2764bit](https://cloud.githubusercontent.com/assets/4411088/21377175/8a8338c8-c76e-11e6-9919-e96caf8fa544.png)
![plip-ubuntu16 04-py27](https://cloud.githubusercontent.com/assets/4411088/21377176/8a86a968-c76e-11e6-92c5-e3402b890dd2.png)

**Comment by ssalentin** [comment]
For the first case, try to rename the **plipcmd** script to **plipcmd.py**. Sometimes, there seem to be issues with the multiprocessing module in Windows when trying to reimport scripts without the .py ending.
For the second case it seems that you don't have a matching version of your Python bindings for OpenBabel installed.

**Comment by o7o** [comment]
Thank you for your reply.
For my second case,  I should uninstall standalone openbabel installation first.
For the first one, as you said, I renamed two files plipcmd to plipcmd.py; in C:\Python27\Scripts and C:\Python27\Lib\site-packages\plip-1.3.3-py2.7.egg\EGG-INFO\scripts.
It's worked like charmed for my all core.
Thanks

**Comment by ssalentin** [comment]
With which parameters did you run PLIP?

**Comment by o7o** [comment]
all as -vtxyp
<pre><code>
v=verbose
t=report in txt
x=report in xml
y=pymol session
p=image
CMIIW
</code></pre>

**Comment by ssalentin** [comment]
Sounds like a problem with PyMOL then. Please start in debug mode (--debug) and post the output here.

**Comment by o7o** [comment]
here the debug result:
<pre><code>Run PLIP

**********************************************
* Protein-Ligand Interaction Profiler v1.3.3 *
**********************************************

Starting analysis of 1bju.pdb
===============================
13 lines automatically fixed in PDB input file.
[EXPERIMENTAL] Input is PDBQT file. Some features (especially visualization) mig
ht not work as expected. Please consider using PDB format instead.
PDB structure successfully read.
Debug:  Pymol Name set as: '1bju'
Debug:  4 ligand(s) after first filtering step.
Debug:  Finalizing extraction for ligand GP6:A:910
Debug:  Number of isomorphisms: 8
Debug:  Finalizing extraction for ligand SO4:A:901
Debug:  Number of isomorphisms: 24
Debug:  Finalizing extraction for ligand DMS:A:300
Debug:  Number of isomorphisms: 4
Debug:  Finalizing extraction for ligand CA:A:246
Debug:  Number of isomorphisms: 1
Analyzing 4 ligands...

GP6 [SMALLMOLECULE] -- GP6:A:910
---------------------------------
Debug:  Number of aromatic ring candidates: 2
  Contains 2 aromatic ring(s).
  Binding site atoms in vicinity (7.5 A max. dist: 164).
Debug:  Number of aromatic ring candidates: 34
  Reduced number of hydrophobic contacts from 2 to 1.
  Ligand interacts with 6 binding site residue(s) in chain(s) A.
  Complex uses 6 hydrogen bond(s), 1 pi-stacking(s), 1 water bridge(s).

SO4 [SMALLMOLECULE] -- SO4:A:901
---------------------------------
  Info:  may be biologically irrelevant
Debug:  Number of aromatic ring candidates: 0
  Binding site atoms in vicinity (7.5 A max. dist: 62).
Debug:  Number of aromatic ring candidates: 34
  Ligand interacts with 3 binding site residue(s) in chain(s) A.
  Complex uses 1 salt bridge(s), 2 hydrogen bond(s).

DMS [SMALLMOLECULE] -- DMS:A:300
---------------------------------
  Info:  may be biologically irrelevant
Debug:  Number of aromatic ring candidates: 0
  Binding site atoms in vicinity (7.5 A max. dist: 58).
Debug:  Number of aromatic ring candidates: 34
  Ligand interacts with 1 binding site residue(s) in chain(s) A.
  Complex uses 1 hydrogen bond(s).

CA [ION] -- CA:A:246
---------------------
Debug:  Number of aromatic ring candidates: 0
  Binding site atoms in vicinity (7.5 A max. dist: 71).
Debug:  Number of aromatic ring candidates: 34
  Ligand interacts with 1 binding site residue(s) in chain(s) A.

Generating visualizations in parallel on 4 cores ...
Finished analysis. Find the result files in bju1/

Press any key to continue . . .
</code></pre>

**Comment by ssalentin** [comment]
Thanks. From the log, I can't see a problem. Is the outputfolder (bju1/ or bju/) completely empty in both cases?

**Comment by o7o** [comment]
Like as I said at first, I got all files of result (-txyp-) at bju folder when I enable maxthreads to 1 (only 1 core). Otherwise, when I used "all" core (more than 1, of course), I just got two kind of files, txt and xml at bju1 folder, there were no .png and .pse.

Any way, thanks for your time and support for this case. I hope, in the future, plip will be running multicore in windows environment.

**Comment by ssalentin** [comment]
Okay, thank you again for the clarification. There are some differences in the fork modules of Unix and Windows systems. We will look into the problem for a future release. I will leave the issue open until then.
