### ISSUE TITLE
Difference between `atoms` and `orig_atoms` attributes

### ISSUE THREAD

**Issue by josejimenezluna** [ssalentin/plip#51]
Hello, first of all thanks for the great package. 

I'm playing around with some of the interaction objects return by the Python package, and I came across the pication and pistack ones:

```
Out[24]: pication(ring=aromatic_ring(atoms=[<pybel.Atom object at 0x7f88b75ee110>,
<pybel.Atom object at 0x7f88b75ee190>, <pybel.Atom object at 0x7f88b75ee210>, <pybel.Atom
object at 0x7f88b75ee310>, <pybel.Atom object at 0x7f88b75ee410>], orig_atoms=[<pybel.Atom
 object at 0x7f88b80f06d0>, <pybel.Atom object at 0x7f88b80f09d0>, <pybel.Atom object at 
0x7f88b80f0990>, <pybel.Atom object at 0x7f88b80f0a90>, <pybel.Atom object at 
0x7f88b80f0b10>], atoms_orig_idx=[224, 225, 226, 228, 230], normal=array([-0.34151512, 
-0.93419256,  0.10320694]), obj=<openbabel.OBRing; proxy of <Swig Object of type 
'OpenBabel::OBRing *' at 0x7f88b80ec0c0> >, center=[5.3118, 22.6008, 35.391999999999996], 
type='5-membered'), charge=lcharge(atoms=[<pybel.Atom object at 0x7f88b6499fd0>], 
orig_atoms=[<pybel.Atom object at 0x7f88b64ad350>], atoms_orig_idx=[5556], type='positive',
 center=[3.28, 19.829, 36.006], fgroup='tertamine'), distance=3.4911434344638432, 
offset=0.9939751145873313, type='regular', restype='HIS', resnr=17, reschain='A', 
restype_l='MOL', resnr_l=1, reschain_l='Z', protcharged=False)
```

I was wondering, what is the difference between the list of atoms in the `atoms` attribute and the one in `orig_atoms`?

**Comment by vjhaupt** [comment]
Hi José,

Great that you are enjoying PLIP. The original atoms are those from the native (PDB) structure. The trouble is that if you create a copy of a ligand in OpenBabel, it will renumber the atoms. This will make some trouble when you want to map e.g. interactions back to the original PDB structure. That’s why these atoms are kept.

Best, Joachim

--
Dr. Joachim Haupt

Head of Technology Development
Project Leader
Redivia, TU Dresden

Tatzberg 47
01307 Dresden
Germany

**Comment by josejimenezluna** [comment]
Hi Joachim, 

Thanks for your swift response. So if I understand correctly, `orig_atoms` refer to the atoms from the provided PDB, while `atoms` refer to those after the renumbering by OpenBabel? The coordinates of these two sets of atoms should still be the same, correct?

Cheers,

**Comment by vjhaupt** [comment]
Yes
