### ISSUE TITLE
Not successful to run PLIP in python 3.5.2 64bit

### ISSUE THREAD

**Issue by o7o** [ssalentin/plip#6]
here the verbose when installed from python setup.py install

> `Microsoft Windows [Version 6.1.7601]
> Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
> 
> C:\Python35\py35whl\plip>python setup.py install
> running install
> running bdist_egg
> running egg_info
> creating plip.egg-info
> writing requirements to plip.egg-info\requires.txt
> writing dependency_links to plip.egg-info\dependency_links.txt
> writing top-level names to plip.egg-info\top_level.txt
> writing plip.egg-info\PKG-INFO
> writing manifest file 'plip.egg-info\SOURCES.txt'
> reading manifest file 'plip.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'plip.egg-info\SOURCES.txt'
> installing library code to build\bdist.win-amd64\egg
> running install_lib
> running build_py
> creating build
> creating build\lib
> creating build\lib\plip
> copying plip\__init__.py -> build\lib\plip
> creating build\lib\plip\modules
> copying plip/modules\chimeraplip.py -> build\lib\plip/modules
> copying plip/modules\config.py -> build\lib\plip/modules
> copying plip/modules\detection.py -> build\lib\plip/modules
> copying plip/modules\mp.py -> build\lib\plip/modules
> copying plip/modules\plipremote.py -> build\lib\plip/modules
> copying plip/modules\plipxml.py -> build\lib\plip/modules
> copying plip/modules\preparation.py -> build\lib\plip/modules
> copying plip/modules\pymolplip.py -> build\lib\plip/modules
> copying plip/modules\report.py -> build\lib\plip/modules
> copying plip/modules\supplemental.py -> build\lib\plip/modules
> copying plip/modules\visualize.py -> build\lib\plip/modules
> copying plip/modules\webservices.py -> build\lib\plip/modules
> copying plip/modules\__init__.py -> build\lib\plip/modules
> creating build\bdist.win-amd64
> creating build\bdist.win-amd64\egg
> creating build\bdist.win-amd64\egg\plip
> creating build\bdist.win-amd64\egg\plip\modules
> copying build\lib\plip\modules\chimeraplip.py -> build\bdist.win-amd64\egg\plip\
> modules
> copying build\lib\plip\modules\config.py -> build\bdist.win-amd64\egg\plip\modul
> es
> copying build\lib\plip\modules\detection.py -> build\bdist.win-amd64\egg\plip\mo
> dules
> copying build\lib\plip\modules\mp.py -> build\bdist.win-amd64\egg\plip\modules
> copying build\lib\plip\modules\plipremote.py -> build\bdist.win-amd64\egg\plip\m
> odules
> copying build\lib\plip\modules\plipxml.py -> build\bdist.win-amd64\egg\plip\modu
> les
> copying build\lib\plip\modules\preparation.py -> build\bdist.win-amd64\egg\plip\
> modules
> copying build\lib\plip\modules\pymolplip.py -> build\bdist.win-amd64\egg\plip\mo
> dules
> copying build\lib\plip\modules\report.py -> build\bdist.win-amd64\egg\plip\modul
> es
> copying build\lib\plip\modules\supplemental.py -> build\bdist.win-amd64\egg\plip
> \modules
> copying build\lib\plip\modules\visualize.py -> build\bdist.win-amd64\egg\plip\mo
> dules
> copying build\lib\plip\modules\webservices.py -> build\bdist.win-amd64\egg\plip\
> modules
> copying build\lib\plip\modules\__init__.py -> build\bdist.win-amd64\egg\plip\mod
> ules
> copying build\lib\plip\__init__.py -> build\bdist.win-amd64\egg\plip
> byte-compiling build\bdist.win-amd64\egg\plip\modules\chimeraplip.py to chimerap
> lip.cpython-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\config.py to config.cpytho
> n-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\detection.py to detection.
> cpython-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\mp.py to mp.cpython-35.pyc
> 
> byte-compiling build\bdist.win-amd64\egg\plip\modules\plipremote.py to plipremot
> e.cpython-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\plipxml.py to plipxml.cpyt
> hon-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\preparation.py to preparat
> ion.cpython-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\pymolplip.py to pymolplip.
> cpython-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\report.py to report.cpytho
> n-35.pyc
>   File "build\bdist.win-amd64\egg\plip\modules\report.py", line 100
>     print et.tostring(self.xmlreport, pretty_print=True)
>            ^
> SyntaxError: invalid syntax
> 
> byte-compiling build\bdist.win-amd64\egg\plip\modules\supplemental.py to supplem
> ental.cpython-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\visualize.py to visualize.
> cpython-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\webservices.py to webservi
> ces.cpython-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\modules\__init__.py to __init__.cp
> ython-35.pyc
> byte-compiling build\bdist.win-amd64\egg\plip\__init__.py to __init__.cpython-35
> .pyc
> creating build\bdist.win-amd64\egg\EGG-INFO
> installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
> running install_scripts
> running build_scripts
> creating build\scripts-3.5
> copying and adjusting plip\plipcmd -> build\scripts-3.5
> creating build\bdist.win-amd64\egg\EGG-INFO\scripts
> copying build\scripts-3.5\plipcmd -> build\bdist.win-amd64\egg\EGG-INFO\scripts
> copying plip.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
> copying plip.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying plip.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
> 
> copying plip.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
> copying plip.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying plip.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
> creating dist
> creating 'dist\plip-1.3.3-py3.5.egg' and adding 'build\bdist.win-amd64\egg' to i
> t
> removing 'build\bdist.win-amd64\egg' (and everything under it)
> Processing plip-1.3.3-py3.5.egg
> creating c:\python35\lib\site-packages\plip-1.3.3-py3.5.egg
> Extracting plip-1.3.3-py3.5.egg to c:\python35\lib\site-packages
>   File "c:\python35\lib\site-packages\plip-1.3.3-py3.5.egg\plip\modules\report.p
> y", line 100
>     print et.tostring(self.xmlreport, pretty_print=True)
>            ^
> SyntaxError: invalid syntax
> 
> Adding plip 1.3.3 to easy-install.pth file
> Installing plipcmd script to C:\Python35\Scripts
> 
> Installed c:\python35\lib\site-packages\plip-1.3.3-py3.5.egg
> Processing dependencies for plip==1.3.3
> Searching for lxml==3.7.0
> Best match: lxml 3.7.0
> Adding lxml 3.7.0 to easy-install.pth file
> 
> Using c:\python35\lib\site-packages
> Searching for numpy==1.11.3+mkl
> Best match: numpy 1.11.3+mkl
> Adding numpy 1.11.3+mkl to easy-install.pth file
> 
> Using c:\python35\lib\site-packages
> Searching for openbabel==2.4.1
> Best match: openbabel 2.4.1
> Adding openbabel 2.4.1 to easy-install.pth file
> 
> Using c:\python35\lib\site-packages
> Finished processing dependencies for plip==1.3.3
> 
> C:\Python35\py35whl\plip>`
> 

Here the result when I typed python plipcmd in Python35 Scripts

> `C:\Python35\Scripts>python plipcmd
> Traceback (most recent call last):
>   File "c:\python35\lib\site-packages\plip-1.3.3-py3.5.egg\EGG-INFO\scripts\plip
> cmd", line 25, in <module>
>     from plip.modules.preparation import *
>   File "C:\Python35\lib\site-packages\plip-1.3.3-py3.5.egg\plip\modules\preparat
> ion.py", line 24, in <module>
>     from detection import *
> ImportError: No module named 'detection'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "plipcmd", line 4, in <module>
>     __import__('pkg_resources').run_script('plip==1.3.3', 'plipcmd')
>   File "C:\Python35\lib\site-packages\pkg_resources\__init__.py", line 719, in r
> un_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "C:\Python35\lib\site-packages\pkg_resources\__init__.py", line 1504, in
> run_script
>     exec(code, namespace, namespace)
>   File "c:\python35\lib\site-packages\plip-1.3.3-py3.5.egg\EGG-INFO\scripts\plip
> cmd", line 33, in <module>
>     from modules.preparation import *
> ImportError: No module named 'modules'
> 
> C:\Python35\Scripts>`
> 

How to resolve this?
I neeed your assisstance, thanks

**Comment by ricrogz** [comment]
`File "c:\python35\lib\site-packages\plip-1.3.3-py3.5.egg\plip\modules\report.p
y", line 100
print et.tostring(self.xmlreport, pretty_print=True)
^
SyntaxError: invalid syntax`

That's your error: a "Python 2" formatted `print` (Python 3 requires parentheses around `print` arguments). I guess PLIP is not written for compatibility with Python 3.

Anyway, why would you do that? As far as I know, pymol has no support for Python 3, so you are probably running into much bigger than that this.

**Comment by o7o** [comment]
<code>That's your error: a "Python 2" formatted print (Python 3 requires parentheses around print arguments). I guess PLIP is not written for compatibility with Python 3.</code>

Thanks for your info, really, I did not know the error mean. I have successful installed and ran PLIP on Ubuntu 16.04 Desktop LTS version in Virtual applications, as I know, this Ubuntu version had python 3.5 as its default python. See screenshot at link: https://goo.gl/PCUFqv
Sorry, I can not show you the screenshot for PLIP on Ubuntu 16.04 at this time. It is in my PC at office. I will check it later.

<code>Anyway, why would you do that? As far as I know, pymol has no support for Python 3, so you are probably running into much bigger than that this.</code>

Officially maybe, I have used an unofficial packages from Gohlke for windows system (here the screenshoot link: https://goo.gl/uZoIbn). In my case, PyMOL 1.8.5.0 ran well in python 3.5. I will show you the screenshoot later.

**Comment by ricrogz** [comment]
Two things learned: I did not know about these ports for Python 3, and neither that there were already builds of PyMOL 1.8.5.0. 

But, anyway, I guess most of the available PyMOL scripts and plugins are designed for the Python 2 builds, and, while some might run flawlessly on Python 3 builds, others will cause a lot of trouble due to the small differences between Python 2 and 3.

So, for now, and unless I had a very good reason for not to, I would stay with the Python 2 PyMOL, at least until an 'official' Python 3 version has been around for some time, and people have had time enough to port their favorite scripts.

**Comment by ricrogz** [comment]
I have to admit you intrigued me. I'm having a second look at PyMOL & PLIP on Python 3. The `print` is the least of the problems, but maybe I can work out something and submit it as a pull request.

**Comment by ssalentin** [comment]
Thank you for the feedback and the discussion.
Right now, PLIP only supports Python 2.x 
Porting the PLIP code to Python 3 is definitely planned for the first half of the next year.
