### ISSUE TITLE
Not a recognised Open Babel descriptor type

### ISSUE THREAD

**Issue by rehanzfr** [ssalentin/plip#8]
Dear, When I run this command

plipcmd -i 1ATP -v 

I got into the problem which is:

 **ValueError: �Ɵ is not a recognised Open Babel descriptor type**

Can you help me

**Comment by ssalentin** [comment]
This error is not related to PLIP is itself. It happens if your Python binding don't match your OpenBabel version. Please try to reinstall OpenBabel with Python bindings.
