### ISSUE TITLE
It worked in version 1.3.3, but Now it did not work in 1.3.4 version for some PDB-ID 

### ISSUE THREAD

**Issue by o7o** [ssalentin/plip#9]
when I used 1.3.3, PDB-ID 1bju gave me all (vptyx) result. after upgrading to 1.3.4, it reported an error:
```
Run PLIP
**********************************************
* Protein-Ligand Interaction Profiler v1.3.4 *
**********************************************
Starting analysis of 1bju.pdb
================================
2217 lines automatically fixed in PDB input file.
Error:  File contains no valid molecules.
```
There was a fix pdb file in output folder (attached as f1bju-locally.pdb) but still give an error. When I downloaded a fix pdb file from https://projects.biotec.tu-dresden.de/plip-web/plip/ for the same PDB-ID / file (attached as f1bju-web.pdb), it worked again like charmed.

This is my system:
`Win 7 32 bit (virtual: 1 core), Python 2.7.12, PyMOL 1.7.6.0, OpenBabel 2.4.1`
Thanks

[f1bju.zip](https://github.com/ssalentin/plip/files/1042762/f1bju.zip)

**Comment by ssalentin** [comment]
Can you try with the latest release from GitHub (PLIP v1.3.4b). This is the same version we have on the server and works for the structure 1bju (I have tested it locally). Otherwise, please try the latest development version from GitHub.

**Comment by o7o** [comment]
I have tested the latest release in my Windows system, but the same error results.

sorry for late information.

**Comment by ssalentin** [comment]
Problem was due to additional carriage return characters probably added from the Windows system. They are now removed before processing.  Fix added to development commit https://github.com/ssalentin/plip/commit/78aedc4bab5c9340cebf7268ce545a7547f7ecbd . Was already tested on the provided files and works now as expected.
